{
 "title": "pgreplay-go",
 "description": "Benchmarking dashboard for https://github.com/gocardless/pgreplay-go",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,15m" },
   {
    "name": "node",
    "query": {
     "query": "label_values(up{port=\"9445\"},  instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Benchmarking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Items Processed/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pgreplay_items_processed_total{instance=\"$node\"}[$interval])",
     "legendFormat": "items/s"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgreplay_connections_active{instance=\"$node\"}",
     "legendFormat": "active"
    },
    {
     "expr": "rate(pgreplay_connections_established_total{instance=\"$node\"}[$interval])",
     "legendFormat": "established/s"
    }
   ]
  },
  {
   "title": "ETA",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_min((1.0 - pgreplay_items_filter_progress_fraction{instance=\"$node\"}) / rate(pgreplay_items_filter_progress_fraction{instance=\"$node\"}[$interval]), 0)"
    }
   ]
  },
  {
   "title": "Progress",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "pgreplay_items_filter_progress_fraction{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "Go Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"$node\"}\nand\npgreplay_connections_active{instance=\"$node\"}",
     "legendFormat": "heap bytes"
    },
    {
     "expr": "go_goroutines{instance=\"$node\"}\nand\npgreplay_connections_active{instance=\"$node\"}",
     "legendFormat": "goroutines"
    }
   ]
  }
 ]
}